# Using the Ubuntu image (our OS)
FROM ubuntu:20.04

# Update package manager (apt-get) 
# and install (with the yes flag `-y`)
# Python and Pip
RUN apt-get update && apt-get install -y \
    python3.8 \
    python3-pip

# Add a user.
#RUN \
#  apt-get update && \  
#  useradd -ms /bin/bash isocmb

#USER isocmb

# Install our Python dependencies
RUN pip install Requests Pygments

# Copy our script into the container
COPY /server.py /server.py

# Run the script when the image is run
#ENTRYPOINT ["python3", "/server.py"]

#CMD ["/bin/bash"]
#ENTRYPOINT ["/bin/sh"]
