FROM tatianameleshko/ubuntu_odbc:latest

RUN pip3 install jupyter==1.0.0 plotly==4.4.1 chart_studio==1.0.0 scipy==1.4.1 sklearn==0.0 matplotlib==3.1.2

CMD ["jupyter","notebook", "--notebook-dir=/home/northendconnect/data_analysis","--ip='0.0.0.0'","--port=8888","--no-browser","--allow-root"]
