version: "3"

services:
  ubuntu:
    build:
    contect: .
    dockerfile: dockerfiles/Dockerfile-Ubuntu
   ports:
    - "1024:1024"
   volumes:
    - /
  jupyter:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-jupyter
    env_file:
      - creds.env
    ports:
      - "8888:8888"
    volumes:
      - NorthEndConnect-Unattended_IPT:/NorthEndConnect-Unattended_IPT
  webserver:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-webserver
    ports:
      - "80:80"
    volumes:
      - /NorthEndConnect-Unattended_IPT/server/www:/usr/share/nginx/html
   
